version: '3'
services:
  nodejs-app:
    image: davep2643279/hello-node-js:latest
    ports:
      - "3008:3008"

  reactjs-app:
    image: davep2643279/hello-react:latest
    ports:
      - "3001:80"

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs-app
      - reactjs-app
