version: '3'
services:
  node-app:
    image: test
    ports:
      - "3000:3000"

  nginx-proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf